TestUngDung/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

TestUngDung/Areas/Admin/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ModelEF.Model;
using PagedList;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class SanPhamController : Controller
    {
        private NgoThanhTuanContext db = new NgoThanhTuanContext();

        // GET: Admin/SanPham
        public ActionResult Index(string searchString, int? page)
        {

            //var sanPhams = db.SanPhams.Include(p => p.Category);
            //return View(sanPhams.ToList());
            var sanPhams = db.SanPhams.Include(p => p.Category);
            return View(sanPhams.Where(x => x.NameProduct.Contains(searchString) || searchString == null).ToList().ToPagedList(page ?? 1, 5));
        }

        // GET: Admin/SanPham/Details/
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.SanPhams.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }


        // GET: Admin/SanPham/Create
        public ActionResult Create()
        {
            ViewBag.IDCategory = new SelectList(db.HangMucs, "IDCategory", "NameCategory");
            return View();
        }

        // POST: Admin/SanPham/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IDCategory,NameProduct,UnitCost,Quantity,Description,StatusProduct")] Product product, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                string fileName = Path.GetFileName(image.FileName);
                string urlImage = Server.MapPath("/Image/" + fileName);
                image.SaveAs(urlImage);
                product.ImageProduct = "/Image/" + fileName;
            }

            if (ModelState.IsValid)
            {
                db.SanPhams.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDCategory = new SelectList(db.HangMucs, "IDCategory", "NameCategory", product.IDCategory);
            return View(product);
        }

        // GET: Admin/SanPham/Delete/
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.SanPhams.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Admin/SanPham/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Product product = db.SanPhams.Find(id);
            db.SanPhams.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestUngDung/Areas/Admin/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ModelEF.DAO;
using ModelEF.Model;
using PagedList;

namespace TestUngDung.Areas.Admin.Controllers
{
    public class UserAccountController : Controller
    {
        private NgoThanhTuanContext db = new NgoThanhTuanContext();

   
        // GET: Admin/UserAccount
        public ActionResult Index(string searchString , int? page)
        {
            
            return View(db.UserAccounts.Where(x => x.UserName.Contains(searchString) || searchString == null).ToList().ToPagedList(page ?? 1 ,5));
        }

     

        // Delete User
        public ActionResult Delete(string id)
        {
            var dao = new UserDao().Delete(id);
            return RedirectToAction("Index");
            // lỗi cái redireect ni lam load laị trang khi dùng ajax
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestUngDung/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ModelEF.Model;


namespace TestUngDung.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            var productDao = new ProductDao();
            ViewBag.NewProducts = productDao.ListNewProduct(10);
            return View();
        }
    }
}

TestUngDung/Areas/Admin/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Trang Quản Trị </h2>

TestUngDung/Areas/Admin/Views/SanPham/Create.cshtml
@model ModelEF.Model.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Thêm Mới Sản Phẩm</h2>

@using (Html.BeginForm("Create", "SanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label>Mã SP</label>
        @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label>Loại SP </label>
        @Html.DropDownList("IDCategory", null, htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IDCategory, "", new { @class = "text-danger" })
        </div>
   
    <div class="form-group">
        <label>Tên Sản Phẩm</label>
        
        @Html.EditorFor(model => model.NameProduct, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.NameProduct, "", new { @class = "text-danger" })
    </div>
   
    <div class="form-group">
        <label>Giá</label>
        @Html.EditorFor(model => model.UnitCost, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.UnitCost, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
       <lable>Số Lượng</lable>
        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
    </div>

    <div>
        <input for="files" type="file" name="Image" id="Image" class="bg-blue text-dark" />
    </div>
    

    <div class="form-group">
        <lable>Mô Tả</lable>
        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>

    <div class="form-group">
        <lable>Trạng Thái</lable>
       
        @Html.EditorFor(model => model.StatusProduct, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.StatusProduct, "", new { @class = "text-danger" })
    </div>
 
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
 
}

<div>
    @Html.ActionLink("Quay Lại", "Index")
</div>

TestUngDung/Areas/Admin/Views/SanPham/Delete.cshtml
@model ModelEF.Model.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashboard.cshtml";
}


<h3>Bạn có chắc muốn xóa sản phẩm này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.NameCategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.NameCategory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnitCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnitCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusProduct)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Quay Lại", "Index")
        </div>
    }
</div>

TestUngDung/Areas/Admin/Views/SanPham/Details.cshtml
@model ModelEF.Model.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Xem Chi Tiết Sản Phẩm</h2>

<div >
    <hr />
    <dl class="row">
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Category.NameCategory)
        </dt>

        <dd class="col-10">
            @Html.DisplayFor(model => model.Category.NameCategory)
        </dd>

        <dt class="col-2">
            @Html.DisplayNameFor(model => model.NameProduct)
        </dt>

        <dd class="col-10">
            @Html.DisplayFor(model => model.NameProduct)
        </dd>

        <dt class="col-2">
            @Html.DisplayNameFor(model => model.UnitCost)
        </dt>

        <dd class="col-10">
            @Html.DisplayFor(model => model.UnitCost)
        </dd>

        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd class="col-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt class="col-2">
            @Html.DisplayNameFor(model => model.ImageProduct)
        </dt>

        <dd class="col-10">
            @Html.DisplayFor(model => model.ImageProduct)
        </dd>

        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd class="col-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="col-2">
            @Html.DisplayNameFor(model => model.StatusProduct)
        </dt>

        <dd class="col-10">
            @Html.DisplayFor(model => model.StatusProduct)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Quay Lại", "Index")
</p>

TestUngDung/Areas/Admin/Views/SanPham/Index.cshtml
@model PagedList.IPagedList<ModelEF.Model.Product>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashboard.cshtml";
}

<link href="~/Public/css/pageList.css" rel="stylesheet" />

<h2>Quản Lý Sản Phẩm  </h2>
<div class="col">
    @using (Html.BeginForm("Index", "SanPham", FormMethod.Get, new { @class = "form-inline" }))
    {
        <div class="form-group col-8">  <input type="text" name="searchString" value="" placeholder="Nhập sản phẩm cần tìm kiếm" class="form-control w-100" /></div>
        <div class="form-group col-4"> <button type="submit" class="btn btn-block btn-default">Tìm Kiếm</button></div>
    }

</div>
<p>
    @Html.ActionLink("Thêm Mới", "Create")
</p>
<div class="table-responsive">
    <table class="table table-bordered  table-hover">
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.Category.NameCategory)*@
                ID
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Category.NameCategory)*@
                Tên Hạng Mục
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.NameProduct)*@
                Tên Sản Phẩm
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.UnitCost)*@
                Giá Sản Phẩm
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Quantity)*@
                Số Lượng
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.ImageProduct)*@
                Ảnh
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.Description)*@
                Mô Tả
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.StatusProduct)*@
                Trạng Thái
            </th>
            <th>Thao Tác</th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.NameCategory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NameProduct)
        </td>
        <td>
            @* Hàm format tiền*@
            @{
                var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
                var unitCost = String.Format(info, "{0:c0}", item.UnitCost);
            }

            @Html.DisplayFor(modelItem => unitCost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            <img src="@item.ImageProduct" alt="@item.NameProduct" style="width:200px; height: 200px; object-fit: cover" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StatusProduct)
        </td>
        <td>
            @Html.ActionLink("Chi Tiết", "Details", new { id = item.ID })
            @Html.ActionLink("Xóa", "Delete", new { id = item.ID })
        </td>
    </tr>
        }

    </table>
</div>
<div class="d-flex justify-content-between">
    <div>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
    <div>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    </div>
</div>

TestUngDung/Areas/Admin/Views/UserAccount/Create.cshtml
@model ModelEF.Model.UserAccount

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserAccount</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusAcc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StatusAcc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StatusAcc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TestUngDung/Areas/Admin/Views/UserAccount/Delete.cshtml
@model ModelEF.Model.UserAccount

@{
    ViewBag.Title = "Xóa Tài Khoản";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashboard.cshtml";
}


<h3>Bạn có chắc muốn xóa user này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusAcc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusAcc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Quay Lại", "Index")
        </div>
    }
</div>

TestUngDung/Areas/Admin/Views/UserAccount/Index.cshtml
@model PagedList.IPagedList<ModelEF.Model.UserAccount>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Quản Lý Tài Khoản";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashboard.cshtml";
}

<link href="~/Public/css/pageList.css" rel="stylesheet" />
<h2>Quản Lý Tài Khoản</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>

<div class="col">
    @using (Html.BeginForm("Index", "UserAccount", FormMethod.Get, new { @class = "table-responsive" }))
    {
        <div class="form-group col-8">  <input type="text" name="searchString" value="" placeholder="Nhập user cần tìm kiếm" class="form-control w-100" /></div>
        <div class="form-group col-4"> <button type="submit" class="btn btn-block btn-default">Tìm Kiếm</button></div>
    }

</div>
<div class="table-responsive">
    <table class="table table-bordered  table-hover">
        <thead>
            <tr>
                <th>
                    @*@Html.DisplayNameFor(model => model.Username)*@
                    Username
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.Password)*@
                    Password
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.StatusAcc)*@
                    StatusACC
                </th>
                <th>Thao Tác</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatusAcc)
                </td>

                @{
                    if (String.Compare(item.StatusAcc, "Blocked", true) == 0)
                    {
                    <td>
                        @Ajax.ActionLink("Xóa", "Delete", new { @id = item.ID }, new AjaxOptions
                   {
                       OnComplete = "$'(#row_" + item.ID + "').remove()",
                       HttpMethod = "Delete"
                   })
                    </td>   
                    }
                    else
                    {
                        <td>Un Delete</td>
                    }
                    
                }

            </tr>
        </tbody>
        }

    </table>
</div>
<div class="d-flex justify-content-between">
      <div>
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>
        <div>
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        </div>
</div>

TestUngDung/Views/Home/Index.cshtml
@{ ViewBag.Title = "Trang Chủ";
                Layout = "~/Views/_Layout/_Layout.cshtml";
                var listNewProducts = (List<ModelEF.Model.Product>)ViewBag.NewProducts; }
@section Slide
{
    <div class="header_slide">
        <div class="header_bottom_left">
            <div class="categories">
                <ul>
                    <h2>Loại Sản Phẩm</h2>
                    <li><a href="#">Bàn Học</a></li>
                    <li><a href="#">Ghế Ngồi</a></li>
                    <li><a href="#">Đồ Decor</a></li>
                    <li><a href="#">Đèn Học</a></li>
                </ul>
            </div>
        </div>
        <div class="header_bottom_right">
            <div class="slider">
                <div id="slider">
                    <div id="mover">
                        <div id="slide-1" class="slide">
                            <div class="slider-img">
                                <a href="preview.html"><img src="~/Public/assets/client/images/slide-1-image.jpg" alt="learn more" /></a>
                            </div>
                            <div class="slider-text">
                                <h1>Clearance<br><span>SALE</span></h1>
                                <h2>UPTo 20% OFF</h2>
                                <div class="features_list">
                                    <h4>Get to Know More About Our Memorable Services Lorem Ipsum is simply dummy text</h4>
                                </div>
                                <a href="preview.html" class="button">Shop Now</a>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="slide">
                            <div class="slider-text">
                                <h1>Clearance<br><span>SALE</span></h1>
                                <h2>UPTo 40% OFF</h2>
                                <div class="features_list">
                                    <h4>Get to Know More About Our Memorable Services</h4>
                                </div>
                                <a href="preview.html" class="button">Shop Now</a>
                            </div>
                            <div class="slider-img">
                                <a href="preview.html"><img src="~/Public/assets/client/images/slide-3-image.jpg" alt="learn more" /></a>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="slide">
                            <div class="slider-img">
                                <a href="preview.html"><img src="~/Public/assets/client/images/slide-2-image.jpg" alt="learn more" /></a>
                            </div>
                            <div class="slider-text">
                                <h1>Clearance<br><span>SALE</span></h1>
                                <h2>UPTo 10% OFF</h2>
                                <div class="features_list">
                                    <h4>Get to Know More About Our Memorable Services Lorem Ipsum is simply dummy text</h4>
                                </div>
                                <a href="preview.html" class="button">Shop Now</a>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
}
<div class="content">
    <div class="content_top">
        <div class="heading">
            <h3>Tất Cả Sản Phẩm</h3>
        </div>
        <div class="see">
            <p><a href="#">See all Products</a></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="section group">
        @foreach (var item in listNewProducts)
        {
        <div class="grid_1_of_4 ~/Public/assets/client/images_1_of_4">
            <a href="priview.html"><img src="@item.ImageProduct" alt="@item.NameProduct" /></a>
            <h2>@item.NameProduct</h2>
            <div class="price-details">
                <div class="price-number">
                    <p><span class="rupees">
                        @{ var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
                        var unitCost = String.Format(info, "{0:c0}", item.UnitCost); }
                        @Html.DisplayFor(modelItem => unitCost)
                </span></p>
                </div>
                <div class="add-cart">
                    <h4><a href="preview.html">Thêm vào giỏ hàng</a></h4>
                </div>
                <div class="clear"></div>
            </div>
            </div>
            }
        </div>
       </div>